---

# secure docker daemon
- hosts: swarm-manager
  roles:
    - role: vertigobr.secure-docker-daemon
      dds_host: "{{ ansible_eth0['ipv4']['address'] }}"
      dds_restart_docker: yes
  tasks:
  - name: "create daemon.json file"
    copy:
      content: '{
          "hosts": ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2376"],
          "tls": true,
          "tlscacert": "/etc/docker/ca.pem",
          "tlscert": "/etc/docker/server-cert.pem",
          "tlskey": "/etc/docker/server-key.pem",
          "tlsverify": true
        }'
      dest: /etc/docker/daemon.json
  - name: just force systemd to reread configs (2.4 and above)
    systemd: daemon_reload=yes
  - name: Restart docker service, in all cases
    service:
      name: docker
      state: restarted
